### ISSUE TITLE
Old Side Bar still halfworking

### ISSUE THREAD

**Issue by ValensHawke** [new-xkit/XKit#1034]
Okay, I ran the update and it seemed to work. But when I refreshed the page, it was still gone. Tried uninstalling it (to reinstall it) and now it won't uninstall either. Just stays at uninstalling for several minutes. 

Only works when I re-enable it but goes away on refresh.

Happening on Chrome.

**Comment by nightpool** [comment]
I can't reproduce this... Do you have any extensions that may be
interfering?

**Comment by ValensHawke** [comment]
I'll start disabling and reenabling one at a time and report back, but nothing new has been installed for a few weeks at least.

**Comment by nightpool** [comment]
(Sorry, to be clear, I meant non-XKit extensions)

**Comment by ValensHawke** [comment]
Ah, then no. But it does appear there is a conflict between extension as I was reenabling and refresh (more like 5 at a time) and something broke it on the last set of reenables.

So far, it seems like when I have the Read Posts extensions enabled, it breaks Old Side Bar.

**Comment by ValensHawke** [comment]
Also, this is only happening on my Dashboard. If I go to a /tagged/tagterm it shows up without a problem.

**Comment by citrusella** [comment]
I'm still having problems related to this, on all pages; I commented on the issue I posted that was closed ( #1029 ), but basically, I'm experiencing the same issues I was, but without the dropdown appearing. I haven't un/installed or disabled anything new since yesterday (and I don't have Read Posts installed at all). Also haven't installed anything non-XKit in any form anytime recently and don't even have any non-XKit extensions that should theoretically affect Tumblr (except Adblock, if you think that could be an issue).

**Comment by ValensHawke** [comment]
Just saw it update to 1.1.7 and... still having the problem. Is there any way I can manually remove it? Since I can't even properly uninstall it and reinstall to see if that will solve the problem?

**Comment by Dhwty** [comment]
Also having this problem on my dash and my activity page. It worked exactly once on each page, after each of the last two updates. And it's not just the dropdown not appearing, if you click the button (which is still there) it pops up and closes in half a second -- which it's supposed to do (I read the JS), to provide the content for the sidebar, so it's... kind of working, a bit. It's just not actually rendering the sidebar. It is still clicking the button, though, so the first click elsewhere on the page does nothing, because that's unclicking the button.
	
Firefox 45.0.1, nothing changed since the last time it worked, before all this tumblr-side fuckery. Updating to 46.0 does not help. Disabling AdBlock does not help. Disabling NoScript made it work for one reload, but re-enabling and re-disabling didn't make it work again. Confirmed that uninstalling Old Sidebar does not actually work, as it hangs instead.
	
Opening the browser console and reloading gives me one xkit-related error: `04:02:21.799 new-xkit:Object {  }1 sandbox.js:340` which doesn't appear to fire when it works, but does when it shits out.

Super interestingly, disabling and re-enabling Old Sidebar, without reloading the page, will make it show up. Reloading the page after getting it to show up will make it stop working again, but disabling and re-enabling it from xkit will make it start working on the current page every time.

**Comment by ValensHawke** [comment]
Okay, I think I have a solution.
Disable all Xkit extensions.
Re-enable Old Side Bar
Uninstall. Old Side Bar (this actually worked)
Restart Browser
Reinstall Old Side Bar
Re-enable Xkit Extensions. 
There's an occasional refresh where it doesn't load but mostly seems to be working.

**Comment by citrusella** [comment]
Didn't fix it for me, but I suppose I could try again.

A curious development that I'm not sure is normal: When I reinstalled Old Sidebar, it was disabled by default but it displayed as working just after the install.

**Comment by nightpool** [comment]
@citrusella that's expected, if it was disabled before you uninstalled it

**Comment by citrusella** [comment]
It's normal to look disabled but be enabled? Or just the disabled part? (Making sure I totally understand. XP)

**Comment by nightpool** [comment]
Oh, just the disabled part... Yeah, that's definitely a bug.

**Comment by ShotgunsAndSass** [comment]
I've done some checking, and occasionally (I can't reproduce what exactly causes this) some extensions will conflict with Old Sidebar. The one I've got 100% down is "Auto Load Images". I've just disabled it for now cause I don't really need it, but I figured I should point it out now I've found it. I'll update with any more conflicts I find.

Hoe this was a help.

**Comment by nightpool** [comment]
I have Auto Load Images and I've never had a problem with Old Sidebar. What
browser are you on?

**Comment by ShotgunsAndSass** [comment]
I'm on Chrome. I may be wrong about what's causing the glitch cause it happens at random now, it will refuse to spawn for a few refreshes and suddenly return.

**Comment by ValensHawke** [comment]
Can confirm what ShotsgunsAndSass says. It isn't nearly as frequent and it will -mostly- spawn. But on Chrome 49, it will occasionally not spawn. Still better than where I was when I opened this thread.

**Comment by estufar** [comment]
Yeah, I can confirm that it does fail occasionally. I'll work on reworking it and making it more robust once I get out of school for the summer.

**Comment by ShotgunsAndSass** [comment]
I've managed to definitely pin down what has caused it on the computer upstairs, I was wrong about the extension. I thought I had it right but it seems it fails whenever I activate Alternate Timestamps, but works fine when it's off. I don't know if anyone can replicate this though, it could be something weird it's doing just for me.

Thanks so much for working so hard to fix it @estufar it's really frustrating when random updates like this do this randomly and this extension is a freaking godsend.

**Comment by ValensHawke** [comment]
Thank you, @estufar. I love this extension and I do apologize if my continual posting added to any stress.

**Comment by estufar** [comment]
Thanks! And don't worry about it, you're good

**Comment by citrusella** [comment]
Mine's still fairly regularly not showing, but I wanted to send a thanks to @estufar like everyone else has. This is one of my favorite extensions, and I'm glad it's around (I don't forget my drafts like I did before I installed it!), even if it doesn't work right now.

**Comment by ShotgunsAndSass** [comment]
The issues with it have gotten worse for me suddenly, I now need to turn old sidebar on and off again to get it to work. I keep looking to try to work out why this is but I can't find any explanation, it's bizarre.

**Comment by lunaris1013** [comment]
I'm having the same issues as everyone else, with the added bonus of needing to double click "next" "previous" and the heart to like anything.  

Windows 7, FF 45.0.2

**Comment by ShotgunsAndSass** [comment]
![image](https://cloud.githubusercontent.com/assets/18859835/15060880/e9f687b2-1326-11e6-9431-f368b760596b.png)
![image](https://cloud.githubusercontent.com/assets/18859835/15060898/0eae5526-1327-11e6-9fc1-94354c13e438.png)
(black boxes in middle of sidebar to protect blogs)

I'm now getting this.. scrollbar like thing on the old sidebar, and I feel like it's not supposed to be there. I don't know if this could provide any clues.

**Comment by nightpool** [comment]
@shotgunsandsass seems like a separate issue. Can you make a new ticket?

**Comment by ShotgunsAndSass** [comment]
Right I don't know if this is just me but it doesn't work at all for me again, I don;t know if anyone else has this but it just stopped working and even if I turn it on/off it does nothing. Is anyone else getting this?

**Comment by snakefeathers** [comment]
I'm having this problem on both Firefox and Chrome. Both are fully updated. The sidebar only sometimes loads in, otherwise its gone and the dropdown sidebar is completely non-functional. So its doing more harm than good. Please help?

**Comment by citrusella** [comment]
@snakefeathers The current workaround is to go to Old Sidebar's settings and toggle it off and back on, but that'll only hold until you refresh and it could break again (you can prolong having to refresh the whole site if you have Soft Refresh on, but even then you'll probably eventually have to "hard" refresh).

**Comment by ravewulf** [comment]
I disabled all my XKit extensions to get it to work and then started re-enabling them to see which one(s) conflicted with Old Sidebar. Out of the extensions I have installed, only Blacklist seems to prevent Old Sidebar from loading. I tried resetting my Blacklist to the default settings with no entries and Old Sidebar still would not load. For now I'm keeping Old Sidebar disabled as I'd rather have Blacklist enabled than not.

**Comment by ShotgunsAndSass** [comment]
@ravewulf Have you tested it with tumblr saviour? Perhaps that can work as a temporary replacement (though there's a chance that that will break it too).

**Comment by ravewulf** [comment]
I haven't used TS in ages. I think I used to have performance issues with it, but I don't know how much that's changed. I'm not bothered about Old Sidebar not working enough to bother trying TS again, so I'll just wait till this is fixed.

**Comment by citrusella** [comment]
Huh, last time I disabled all extensions except old sidebar at one point and it still only worked intermittently. But that might have been before an update to the extension. Huh.

**Comment by SirJorb** [comment]
Still having this issue where I have to keep disabling and re-enabling the extension for it to work.

**Comment by nightpool** [comment]
Should be fixed by #1302. Let us know if you're still seeing this after updating to old sidebar 1.2.0!

**Comment by citrusella** [comment]
I don't know if this should be noted here or in a new issue, but the update made my sidebar push the content area of my dash (the part where the new post buttons and actual posts are) down so that it doesn't show up until below the Tumblr Radar.

I do have the dashboard-narrowing extension active, though. (But the real rub is that this problem is apparently preventing my access to the XKit menu (clicking the icon does nothing... actually now that I'm testing none of the icons on my dash do anything) so I can't disable it to see if that fixes it unless there's a way to do it on the "backside" (which I think I remember there being but I need to go find it, if it existed).)

**Comment by nightpool** [comment]
Can you repost this in #1303? Thanks!
