### ISSUE TITLE
Safari Private Browsing breaks XHR with cookies

### ISSUE THREAD

**Issue by sinister-sword** [new-xkit/XKit#1147]
Safari in Private Browsing or with cookies set to "Allow from current website only" doesn't allow XHR requests we make to tumblr to include cookies. This breaks OCP, editable reblogs, and probably a ton of other stuff. (anything relying on /svc/ endpoints)

---

original text:

> I've found that Editable Reblogs doesn't work for me in Safari. I've tried disabling all other browser extensions and uninstalling all other extensions from New XKit, but no luck. When I click the blue button to publish/save/etc. the post, it flashes but nothing else happens.

**Comment by hobinjk** [comment]
@sinister-sword I'm unable to reproduce locally. I'm using macOS Sierra, Safari version 10.0, New XKit 7.7.2, and Editable Reblogs version 3.1.0.

What versions of these are you running? (no need to upgrade to Sierra, just want to know what environment I should be testing on)

**Comment by sinister-sword** [comment]
The same, except I'm using macOS Sierra v. 10.12 Beta. Could it be because of that, maybe?

**Comment by sinister-sword** [comment]
I think it's something to do with Safari's cookies and website data settings in the privacy options.. New XKit won't let me post if I've got "Allow from current website only" selected. I also can't post in a private window.

**Comment by nightpool** [comment]
This is probably solved with the new build, but if its not we'll look into seeing if this is something we can fix.

**Comment by sinister-sword** [comment]
I've installed 3.1.1 and I'm still seeing the issue in Safari in private mode or with "Allow from current website only" selected. If no one else can reproduce it, though, it's probably just me.

**Comment by nightpool** [comment]
I can confirm this, but I took some time poking around and couldn't find any way to fix it. Maybe we need to be using a different global script?

**Comment by AprilSylph** [comment]
*should* be resolved by #1543 since OCP/ER use injected XHRs now
