### ISSUE TITLE
AccessKit post text title font size doesn't increase

### ISSUE THREAD

**Issue by kitsunegari101** [new-xkit/XKit#476]
I've noticed that as of late, the font size increase in AccessKit seems to be having issues; post text looks fine (as in after a page refresh it changes to the normal font) but post title text doesn't change at all, instead staying the same size as the post text itself. Only way I've found around it is to untick the box next to the font size increase box, but it's not any easier on my terrible eyesight which is why I have AccessKit in the first place. Any help would be appreciated. c:

**Comment by 0xazure** [comment]
Closing as duplicate of #424, and this was fixed in #470.

Outdated extensions can usually be forced to update by navigating to the 'Other' tab in the XKit interface and clicking on 'Update all my extensions'.

**Comment by nightpool** [comment]
@kitsunegari101 If you're not seeing this fix, confirm that you're on XKit
7.7.0

if you're not, you can update here for firefox
<http://new-xkit-extension.tumblr.com/firefox> and here for chrome
<http://new-xkit-extension.tumblr.com/chrome>.

**Comment by kitsunegari101** [comment]
Currently on 7.7.0; no changes so far.

**Comment by 0xazure** [comment]
@kitsunegari101 please verify that you are using AccessKit version `1.1.6`.  XKit extension versions can be seen by navigating to the 'My XKit' tab in the interface, scrolling to the extension (in this case, AccessKit), and inspecting the version number to the right of the extension name as seen below:

![capture](https://cloud.githubusercontent.com/assets/1041456/9773177/d6567ba6-570e-11e5-971d-7431711955d1.PNG)

**Comment by kitsunegari101** [comment]
Definitely on 1.1.6; for now, I've disabled the font size increase until a fix is found (at least, for me).

**Comment by 0xazure** [comment]
I'm not able to reproduce the issue.  You'd said

> but post title text doesn't change at all, instead staying the same size as the post text itself.

but post titles appear large even without AccessKit installed.  Could you attach a screenshot of the behaviour you're seeing and elaborate on what you're expecting to see?

**Comment by kitsunegari101** [comment]
Knew I'd forgotten something in the OP; thanks for the reminder.

Here's the post title text with font size increase turned off:

![size increase off](https://cloud.githubusercontent.com/assets/14188767/9780547/f8a4de82-574f-11e5-8593-0344c71bae87.png)

And here it is with it turned on:

![size increase on](https://cloud.githubusercontent.com/assets/14188767/9780552/05682296-5750-11e5-92fb-d0ab572322d1.png)

**Comment by blackjackkent** [comment]
Damn... I guess post titles in the new reblog layout are differently styled. I'll look at this tomorrow. Reopening the issue and claiming.

**Comment by blackjackkent** [comment]
Turned out my previous fix actually bugged titles. So this one's my fault. Fix in #482 should solve it.

**Comment by kitsunegari101** [comment]
Still having the same issue, but I think it might just be my browser screwing up. :/

**Comment by blackjackkent** [comment]
Can you verify that you've moved to a new version of AccessKit?
