### ISSUE TITLE
Post aren't hidden if they're AlreadyReblogged on the dashboard

### ISSUE THREAD

**Issue by bvtsang** [new-xkit/XKit#542]
Steps to reproduce:

1. In One-Click Postage, enable AlreadyReblogged
2. Enable "Hide posts if they're AlreadyReblogged on my dashboard"
3. Visit your dashboard and reblog a post that has already been reblogged
4. Hover your mouse over the reblog icon and reblog that post
5. Refresh your dashboard
6. Expect that the post you reblogged from is hidden
7. Observe that the post you reblogged from is still visible

**Comment by Wolvan** [comment]
Fixed once #533 gets merged

**Comment by bvtsang** [comment]
I had someone try the tentative fix to #533, but this issue still persisted.

**Comment by Wolvan** [comment]
Did they install only the updated ``one_click_reblog.js`` or also ``xkit_patches.js``? Storing the root ID depends on ``xkit_patches.js`` to return the proper ``root_id``

**Comment by bvtsang** [comment]
They only updated One Click Reblog.

I just tested this with xkit_patches, and I'll safely say #533 does indeed fix this.
